### PR TITLE
Feature/object interactions

### PR DESCRIPTION
**Pull request by KrisNumber24**
Base classes to create switch and activable objects.

### CODE REVIEW

**Comment by KrisNumber24** [comment]
On/Off Activator are now available for test ! :raised_hands:

**Comment by pierrechls** [comment]
Great job @KrisNumber24 👏

**Comment by KrisNumber24** [comment]
I found a bug with PressurePlate collision. I am working to fix that ! 💪

**Comment by KrisNumber24** [comment]
🕐 Branch is ready for testing !

**Comment by pierrechls** [comment]
Tu veux que je test @KrisNumber24 ?

**Comment by KrisNumber24** [comment]
Je veux bien si tu as le time @pierrechls

**Review by pierrechls — APPROVED** [review]
Awesome work @KrisNumber24 ❤️  👍

**Pull request merged**
